### ISSUE TITLE
Not working for Singapore numbers

### ISSUE THREAD

**Issue by ruchernchong** [krestaino/prankstr#1]
I believe that this works **only** for US numbers?

**Comment by krestaino** [comment]
Ah, whoops. Sorry bout that. I had to enable other countries within the Twilio dashboard. Just enabled the whole world access!

Though this app will die once the Twilio credits run out. Was only a fun project to test out Twilio and Google Cloud Text-to-Speech. This app will surely be abused and I have no desire to keep it GDPR compliment or endure the privacy and legal concerns with this type of app.

Some of the messages people have sent so far, yikes!

**Comment by ruchernchong** [comment]
This is something interesting and fun!
